### PR TITLE
setup.py → pyproject.toml

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by servoz** [comment]
I'm also planning to scrap the old way of doing things (setup.py) to comply with the new recommendations (pyproject.toml). One of the reasons I've been waiting is how to get the version into a python script from pyproject.toml?

**Comment by DimitriPapadopoulos** [comment]
Most importantly:
> `importlib.metadata` operates on third-party _distribution packages_ installed into Python’s `site-packages` directory via tools such as [pip](https://pypi.org/project/pip/). Specifically, it works with distributions with discoverable `dist-info` or `egg-info` directories, and metadata defined by the [Core metadata specifications](https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata).

**Comment by sapetnioc** [comment]
This was my first intention but this file is not installed in the project by standard installer such as `pip`.

**Comment by DimitriPapadopoulos** [comment]
It's probably best to move to the standard Python way for pure Python packages.

**Comment by servoz** [comment]
oh i see ! it's really painful...

**Comment by servoz** [comment]
I think I'll wait a little longer ...

**Comment by sapetnioc** [comment]
I agree with you @DimitriPapadopoulos, the best way for brainvisa-cmake is to switch to standard tools. But there is another aspect of the solution: how much work it represents and who is willing to spend it.

I just checked and I am able to make `importlib.metadata.version('populse_db')` work in brainvisa-cmake by just creating a `<build-or-install-directory>/lib/python<version>/site-packages/populse_db.dist-info/METADATA` file with the following content:
```
Name: populse_db
Version: 3.0.0
```
Building such a minimal `*.dist-info` directory is not what I call a clean solution. But can easily and quickly be done from brainvisa-cmake. And it concerns only brainvisa-cmake. It will still be possible to use standard tools that generates real metadata. So I will start with that workaround and we will have to switch to standard tools to make pip or Conda packages.

**Comment by DimitriPapadopoulos** [comment]
Sure, small steps are better than a large change.

**Comment by sapetnioc** [comment]
The use of `pyproject.toml` is starting to work using brainvisa-cmake (not in the master branch yet, we still have to wait to merge this PR). 

I was able to use `pip install [-e] <source_dir>` with this PR source. And I added some code to set the module version based on the version defined in `pyproject.toml`.

**Comment by servoz** [comment]
Why do you not use `version` as a dynamic metada in pyproject.toml?
dynamic = ["version"]
I planed to use it ...

**Comment by sapetnioc** [comment]
Well, just because I do not know anything yet about dynamic metadata. I must have a look. In fact, @DimitriPapadopoulos put it in this PR but I removed it because `pip` fail if it exists at the same time as `version`.

**Comment by servoz** [comment]
Ah ok ! 
I haven't had time to look at the documentation on the subject either, so I'm keen to hear anything ;-)
Thanks for the tip!

**Comment by sapetnioc** [comment]
`dynamic = ["version"]` just makes it possible not to declare a version in `pyproject.toml`. But the version has to be given somewhere. Some tools, such as setuptools used by `pip`, allow to get this version from a Python module. But I see several drawbacks to do it that way:
- Version is only accessible via the use of specific tools. Therefore, `pyproject.toml` must be customized (within a `[tool.<something>]` section) for each targeted tool.
- brainvisa-cmake would have to find a way to read and interpret the version defined for a specific tool (e.g. setuptools). Or definitions must be added in a brainvisa-cmake specific section such as `[tool.brainvisa-cmake]`. 
- In some use cases we need, for package selection, to access the version from the source directory. If the version is in a module, this module must be properly installed to be able to get the version.
- Project custom Python code must be executed to install a package. AFAIK, one of the reasons to use `pyproject.toml` instead of `setup.py` is to avoid this code execution due to security issues.
- To my opinion, it is more confortable to have all metadata (including version) at the same place.

**Comment by denisri** [comment]
Digression:
If I understand, `pyproject.toml` has been introduced to avoid running python code, which could contain vulnerabilities, but it allows to run python code to get dynamic values. So it seems to totally break the initial reason for `pyproject.toml`, or am I missing something ? Sometimes I have difficulties to understand all the brilliant [r]evolutions in software design which quite often forces us to adapt or rewrite our codes... Our wonderful world is full of _Shadoks_ :)

**Comment by DimitriPapadopoulos** [comment]
No, "pyproject.toml" does not run Python code. The more or less standard deployment solution you use, which can be written in Python or Rust or anything else will read pyproject.toml and  take care of everything. Do just need to trust the deployment solution you have chosen, not Python code shipping with the the Python module you're trying to install.

**Comment by DimitriPapadopoulos** [comment]
You misunderstand `dynamic = ["version"]`. Mainly:
- Either you hardcode the module version in `pyproject .toml`,
- or you let whatever deployment solution you rely on guess it, typically in the version control tools you use. That's what most new projects do, and what makes sense in terms of software supply chain security.

**Pull request merged**
