### PR TITLE
drop support for Python 2.6

### PR DESCRIPTION
**Pull request by ylep**

### CODE REVIEW

**Comment by servoz** [comment]
no problem for me to give up unittest2 import  because we no longer do CI tests for 2.6 (this must be a forgotten residue!).
However what bothers me is that the tests don't work with Mac OS ... I haven't yet taken the time to look at what's wrong. Please, can you do it ?

**Comment by sapetnioc** [comment]
I believe the Mac test failure is not related to this PR but to the way the Mac testing container is installed. I restarted the master branch tests on Mac on TravisCI to see if the error could come from a side effect due to a modification in the system. Wait and see...

I could work on this PR but I need to be able to modify the testing files (they are not modified by this PR). @ylep, is it possible to move this PR on a branch of this project because I suppose that I cannot modify files on your fork.

**Comment by sapetnioc** [comment]
The Mac test failed. Therefore the issue is already on master branch. We will have to fix it independently of this PR. I propose to merge the PR and then work on master.

I do know very little about Mac and the way to install Python and dependencies. I am not sure I will put this on the top of the todo list since it is not a problem with the code but with Mac installation. It makes the projects appear to be unclean and it will have to be fixed but, in fact, populse_db is working well.

**Comment by denisri** [comment]
The error on travis-ci occurs when installing python 3.7 on Mac from brew. Actually I have seen it before: they switched to 3.8 and removed 3.7 (!) so we have to upgrade also. I have done so for soma-workflow.

**Comment by servoz** [comment]
Oh ! Thanks !!! You're absolutely right and it has nothing to do with this PR because I see that the last commit of December 18th was already in error with that damn MacOS!

**Pull request merged**
