### PR TITLE
Make code compatible with PEP8

### PR DESCRIPTION
**Pull request by sapetnioc**
I renamed modules, used autopep8 on modules, checked code with pep8 command, manually formated some lines and improved temporary directory management in tests.

### CODE REVIEW

**Comment by sapetnioc** [comment]
I just updated the pull request because some changes were done on master.

**Comment by ouvrierl** [comment]
Am I supposed to see the comments on the source code or you wrote it somewhere else?

**Comment by sapetnioc** [comment]
No, I just did this PR to have your feedback about files renaming and code formatting for PEP8. Unfortunately, I took my notes in an old fashioned but fast way : with a pen and a paper. These notes can hardly be read and can be understood only by me. This is why I proposed a meeting to give you clear proposals and questions.

**Comment by ouvrierl** [comment]
Ok no problem, it will be faster that way anyway.

**Comment by sapetnioc** [comment]
The important point is to merge this PR (with modification if necessary) before doing modification on master because many lines of codes have changed and merging could be difficult.

**Comment by sapetnioc** [comment]
Ok, you just pushed a commit while I was typing my previous message and there is now a conflict that I have to manage.

**Comment by ouvrierl** [comment]
I removed my last commit and merged the pull request.
I hope I did the right thing.
I will see tomorrow to add my commit again, it wasn't important.

**Pull request merged**
